### ISSUE TITLE
Do not compile with Visual Studio 2015

### ISSUE THREAD

**Issue by Glyco898989** [joshlang/Secp256k1.NET#2]
Do not compile with Visual Studio 2015 (I had never a problem with visual studio 2013):

Severity Code Description Project File Line
Error LNK2019 unresolved external symbol __imp___iob_func referenced in function __gmp_assert_header Secp256k1.NET E:****\Secp256k1.NET-master\libgmp.a(assert.o) 1
Error LNK2019 unresolved external symbol fprintf referenced in function __gmp_assert_header Secp256k1.NET E:\*\Secp256k1.NET-master\libgmp.a(assert.o) 1
Error LNK2001 unresolved external symbol __imp___iob_func Secp256k1.NET E:\*\Secp256k1.NET-master\libgmp.a(memory.o) 1
Error LNK2001 unresolved external symbol fprintf Secp256k1.NET E:\*\Secp256k1.NET-master\libgmp.a(memory.o) 1
Error LNK1120 2 unresolved externals Secp256k1.NET E:\****\Secp256k1.NET-master\x64\Debug\Secp256k1.NET.dll 1

Does someone have a solution and could upgrade the repository to make it work with visual studio 2015?

**Comment by joshlang** [comment]
I grabbed the latest copy of sipa's secp256k1 source and compiled it directly with Visual Studio for you.  The .NET interface is nearly identical (I removed the method to verify public keys).

It's now a C++ .NET assembly with no dependencies on externally built files.  This means it will also work on both 32 and 64 bit systems (switch 32/64 under the project properties as needed).  Unfortunately, AnyCPU isn't an option.

I have done almost no testing at all on this new version.  Please use it with caution :)

Once thing I did notice is that the signatures will be ~70 bytes long, DER encoded.  I had expected ~64 bytes.  *shrug*
